services:
  backend:
    image: ${DOCKERHUB_USERNAME}/maesu-backend:latest
    container_name: maesu-backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SUPABASE_JWK_SET_URI=${SUPABASE_JWK_SET_URI}
    restart: unless-stopped
